//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECOmaintainLOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcoSticker
    {
        public string Id { get; set; }
        public string VCId { get; set; }
        public string CarId { get; set; }
        public string Brand { get; set; }
        public string VINNO { get; set; }
        public string Model { get; set; }
        public string Grade { get; set; }
        public string CompanyInfo { get; set; }
        public string Img_Thumnail { get; set; }
        public string Img_Picture { get; set; }
        public string Stk_Picture { get; set; }
        public string Stk_Pdf { get; set; }
        public string Privatekey { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    }
}
