//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECOmaintainLOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Print
    {
        public string Id { get; set; }
        public string VCId { get; set; }
        public string PrinterName { get; set; }
        public string PrintBy { get; set; }
        public string VINNo { get; set; }
        public string ConfirmBy { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string Remark { get; set; }
    }
}
