//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECOmaintainLOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_VINNO
    {
        public string Id { get; set; }
        public string VCId { get; set; }
        public string VINNO { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public string Status { get; set; }
        public string StickerRef { get; set; }
        public string StorageMethod { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
