//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECOmaintainLOG
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ECO_STICKEREntities : DbContext
    {
        public ECO_STICKEREntities()
            : base("name=ECO_STICKEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EcoSticker> EcoStickers { get; set; }
        public virtual DbSet<Log_Print> Log_Print { get; set; }
        public virtual DbSet<Mapping_RoleUser> Mapping_RoleUser { get; set; }
        public virtual DbSet<Master_Printer> Master_Printer { get; set; }
        public virtual DbSet<Master_Role> Master_Role { get; set; }
        public virtual DbSet<Master_User> Master_User { get; set; }
        public virtual DbSet<Master_VC> Master_VC { get; set; }
        public virtual DbSet<Master_VINNO> Master_VINNO { get; set; }
        public virtual DbSet<Sys_Config> Sys_Config { get; set; }
        public virtual DbSet<Sys_FileAttach> Sys_FileAttach { get; set; }
        public virtual DbSet<Transaction_Log> Transaction_Log { get; set; }
    
        public virtual ObjectResult<Transaction_Log> SP_getTransaction_Log(string rVIN, string rDateFrom, string rDateTo, string rStatus)
        {
            var rVINParameter = rVIN != null ?
                new ObjectParameter("rVIN", rVIN) :
                new ObjectParameter("rVIN", typeof(string));
    
            var rDateFromParameter = rDateFrom != null ?
                new ObjectParameter("rDateFrom", rDateFrom) :
                new ObjectParameter("rDateFrom", typeof(string));
    
            var rDateToParameter = rDateTo != null ?
                new ObjectParameter("rDateTo", rDateTo) :
                new ObjectParameter("rDateTo", typeof(string));
    
            var rStatusParameter = rStatus != null ?
                new ObjectParameter("rStatus", rStatus) :
                new ObjectParameter("rStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Transaction_Log>("SP_getTransaction_Log", rVINParameter, rDateFromParameter, rDateToParameter, rStatusParameter);
        }
    
        public virtual ObjectResult<Transaction_Log> SP_getTransaction_Log(string rVIN, string rDateFrom, string rDateTo, string rStatus, MergeOption mergeOption)
        {
            var rVINParameter = rVIN != null ?
                new ObjectParameter("rVIN", rVIN) :
                new ObjectParameter("rVIN", typeof(string));
    
            var rDateFromParameter = rDateFrom != null ?
                new ObjectParameter("rDateFrom", rDateFrom) :
                new ObjectParameter("rDateFrom", typeof(string));
    
            var rDateToParameter = rDateTo != null ?
                new ObjectParameter("rDateTo", rDateTo) :
                new ObjectParameter("rDateTo", typeof(string));
    
            var rStatusParameter = rStatus != null ?
                new ObjectParameter("rStatus", rStatus) :
                new ObjectParameter("rStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Transaction_Log>("SP_getTransaction_Log", mergeOption, rVINParameter, rDateFromParameter, rDateToParameter, rStatusParameter);
        }
    }
}
