//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECOmaintainLOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Log
    {
        public string LogId { get; set; }
        public string FileProcessName { get; set; }
        public string XMLContent { get; set; }
        public System.DateTime ProcessDate { get; set; }
        public string ConsoleMsg { get; set; }
        public string Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
